[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.19.0"
bson = { version = "2", features = ["chrono-0_4"] }
chrono = { version = "0.4.44", features = ["serde"] }
dotenvy = "0.15.7"
futures = "0.3"
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
mongodb = "3.6.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.52.1", features = ["full"] }
