import { createServer } from "http";
import { handler } from "./build/handler.js"; // generated by adapter-node

const port = process.env.PORT || 3000;

createServer(handler).listen(port, () => {
  console.log(`Server running on port ${port}`);
});
